In [ ]:

# Import useful libraries and classes.
from urllib.request import urlopen as uReq
from bs4 import BeautifulSoup as soup
from dis import dis
from xmlrpc.client import Boolean
import pandas as pd

battery = []
model = []
price = []
discount = []
camera = []
ram = []
display = []

class Source:
    containers = []
    def __init__(self,containers):
        self.containers = containers

    def extract(self,):
        for container in self.containers:
            # inserting model name in the list
            model_name = container.findAll("div", {"class": "_4rR01T"})
            model.append(model_name[0].text.strip())
            # inserting price and discount similarly
            price_model = container.findAll("div", {"class": "_30jeq3 _1_WHN1"})
            price.append(price_model[0].text.strip())

            info = container.findAll("li", {"class": "rgWa7D"}) 
            ram.append(info[0].text.strip().split(' ', 1)[0])
            display.append(info[1].text.strip().split(' ', 1)[0])
            camera.append(info[2].text.strip())
            battery.append(info[3].text.strip().split(' ', 1)[0])



            discount_percent = container.findAll("div", {"class": "_3Ay6Sb"})
            # discount.append(discount_percent[0].text.strip())
            if discount_percent == []:
                discount.append("Null")
            else:
                discount.append(discount_percent[0].text)

# html page upload and read in web_page variable.
my_url = "https://www.flipkart.com/search?p%5B%5D=facets.brand%255B%255D%3DSamsung&sid=tyy%2F4io&sort=recency_desc&wid=1.productCard.PMU_V2_1&page=1"

for i in range(1,11):     # to check change the variable to 3 or 4
    my_url = my_url[:-1] + f'{i}'

    web_page = uReq(my_url)
    page_html = web_page.read()
    # html parser. It is to beautify the HTML code.
    page_soup = soup(page_html)
    # page_soup

    # read class attribute from web page in containers variable.
    # Print the length of containers.   
    containers = page_soup.findAll("div", {"class": "_2kHMtA"})  
    print(len(containers))
    cs1 = Source(containers)
    cs1.extract()
    ############################################################################################



for container in containers:
    # inserting model name in the list
    model_name = container.findAll("div", {"class": "_4rR01T"})
    model.append(model_name[0].text.strip())
    # inserting price and discount similarly
    price_model = container.findAll("div", {"class": "_30jeq3 _1_WHN1"})
    price.append(price_model[0].text.strip())

    info = container.findAll("li", {"class": "rgWa7D"}) 
    ram.append(info[0].text.strip().split(' ', 1)[0])
    display.append(info[1].text.strip().split(' ', 1)[0])
    camera.append(info[2].text.strip())
    battery.append(info[3].text.strip().split(' ', 1)[0])



    discount_percent = container.findAll("div", {"class": "_3Ay6Sb"})
    # discount.append(discount_percent[0].text.strip())
    if discount_percent == []:
        discount.append("Null")
    else:
        discount.append(discount_percent[0].text)

df = pd.DataFrame(list(zip(model, battery, camera,display,ram ,price, discount)), columns=["Model", "Battery(mah)", "Camera","Display Size", "Ram", "Price", "Discount"])

df

file_name = "Flipkart_Samsung.xlsx"

df.to_excel(file_name)

24
24
24
24
24
24
24
24
24
24

In [ ]:
# Import useful libraries and classes.
from urllib.request import urlopen as uReq
from bs4 import BeautifulSoup as soup
from dis import dis
from xmlrpc.client import Boolean
import pandas as pd

In [ ]:
battery = []
model = []
price = []
discount = []
camera = []
ram = []
display = []

In [ ]:
class Source:
    containers = []
    def __init__(self,containers):
        self.containers = containers

In [ ]:
 def extract(self,):
        for container in self.containers:
            # inserting model name in the list
            model_name = container.findAll("div", {"class": "_4rR01T"})
            model.append(model_name[0].text.strip())
            # inserting price and discount similarly
            price_model = container.findAll("div", {"class": "_30jeq3 _1_WHN1"})
            price.append(price_model[0].text.strip())

            info = container.findAll("li", {"class": "rgWa7D"}) 
            ram.append(info[0].text.strip().split(' ', 1)[0])
            display.append(info[1].text.strip().split(' ', 1)[0])
            camera.append(info[2].text.strip())
            battery.append(info[3].text.strip().split(' ', 1)[0])



            discount_percent = container.findAll("div", {"class": "_3Ay6Sb"})
            # discount.append(discount_percent[0].text.strip())
            if discount_percent == []:
                discount.append("Null")
            else:
                discount.append(discount_percent[0].text)

In [ ]:
# html page upload and read in web_page variable.
my_url = "https://www.flipkart.com/search?p%5B%5D=facets.brand%255B%255D%3DSamsung&sid=tyy%2F4io&sort=recency_desc&wid=1.productCard.PMU_V2_1&page=1"

In [ ]:
for i in range(1,11):     # to check change the variable to 3 or 4
    my_url = my_url[:-1] + f'{i}'

    web_page = uReq(my_url)
    page_html = web_page.read()
    # html parser. It is to beautify the HTML code.
    page_soup = soup(page_html)
    # page_soup

    # read class attribute from web page in containers variable.
    # Print the length of containers.   
    containers = page_soup.findAll("div", {"class": "_2kHMtA"})  
    print(len(containers))
    cs1 = Source(containers)
    cs1.extract()

24

AttributeError: ignored

In [ ]:
for container in containers:
    # inserting model name in the list
    model_name = container.findAll("div", {"class": "_4rR01T"})
    model.append(model_name[0].text.strip())
    # inserting price and discount similarly
    price_model = container.findAll("div", {"class": "_30jeq3 _1_WHN1"})
    price.append(price_model[0].text.strip())

    info = container.findAll("li", {"class": "rgWa7D"}) 
    ram.append(info[0].text.strip().split(' ', 1)[0])
    display.append(info[1].text.strip().split(' ', 1)[0])
    camera.append(info[2].text.strip())
    battery.append(info[3].text.strip().split(' ', 1)[0])



    discount_percent = container.findAll("div", {"class": "_3Ay6Sb"})
    # discount.append(discount_percent[0].text.strip())
    if discount_percent == []:
        discount.append("Null")
    else:
        discount.append(discount_percent[0].text)

In [ ]:
df = pd.DataFrame(list(zip(model, battery, camera,display,ram ,price, discount)), columns=["Model", "Battery(mah)", "Camera","Display Size", "Ram", "Price", "Discount"])

In [ ]:
df

,Model,Battery(mah),Camera,Display Size,Ram,Price,Discount
0,"SAMSUNG Galaxy A03 Core (Onyx, 32 GB)",5000,8MP Rear Camera,16.51,2,"₹6,770",35% off
1,"SAMSUNG Galaxy S23 Ultra 5G (Phantom Black, 25...",5000,200MP + 10MP + 12MP + 10MP | 12MP Front Camera,17.27,12,"₹1,24,999",16% off
2,"SAMSUNG Galaxy S23 Plus 5G (Phantom Black, 256...",4700,50MP + 10MP + 12MP | 12MP Front Camera,16.76,8,"₹94,999",18% off
3,"SAMSUNG Galaxy S23 Plus 5G (Cream, 256 GB)",4700,50MP + 10MP + 12MP | 12MP Front Camera,16.76,8,"₹94,999",18% off
4,"SAMSUNG Galaxy S23 Ultra 5G (Green, 512 GB)",5000,200MP + 10MP + 12MP + 10MP | 12MP Front Camera,17.27,12,"₹1,34,999",16% off
...,...,...,...,...,...,...,...
259,"SAMSUNG Galaxy A21s (Blue, 128 GB)",5000,48MP + 8MP + 2MP + 2MP | 13MP Front Camera,16.51,6,"₹16,690",Null
260,"SAMSUNG Galaxy M31s (Mirage Black, 128 GB)",6000,64MP Rear Camera,16.51,6,"₹19,490",15% off
261,"SAMSUNG Galaxy M31 (Ocean Blue, 128 GB)",6000,64MP + 8MP + 5MP + 5MP | 32MP Front Camera,16.26,8,"₹18,700",Null
262,"SAMSUNG Galaxy M01s (Gray, 32 GB)",4000,13MP + 2MP | 8MP Front Camera,15.75,3,"₹10,899",Null
263,"SAMSUNG Galaxy A21s (Black, 64 GB)",5000,48MP + 8MP + 2MP + 2MP | 13MP Front Camera,16.51,4,"₹14,060",Null

In [ ]:
file_name = "Flipkart_Samsung.xlsx"

df.to_excel(file_name)